# Default values for nextcloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tonyby/nextcloud
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: Always

env:
  - name: TZ
    value: Europe/Minsk
  - name: NEXTCLOUD_URL
    value: http://cloud.k8s-19.sa  
  - name: MYSQL_HOST
    value: 192.168.203.19
  - name: MYSQL_USER
    value: nextcloud
  - name: MYSQL_PASSWORD
    value: nextcloud
  - name: MYSQL_DATABASE
    value: nextcloud_test
  - name: NEXTCLOUD_ADMIN_USER
    value: admin
  - name: NEXTCLOUD_ADMIN_PASSWORD
    value: admin
  - name: NEXTCLOUD_TRUSTED_DOMAINS
    value: "cloud.k8s-19.sa cloud.k8s-19.sa"

service:
  #type: ClusterIP
  port: 80

ingress:
  enabled: enable
  className: ""
  annotations: 
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/server-alias: "cloud.k8s-19.sa"
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: cloud.k8s-19.sa
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
    limits:
     cpu: 1000m
     memory: 512Mi
    requests:
     cpu: 500m
     memory: 128Mi

persistentVolume:
    storage: 5Gi


# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80

# nodeSelector: {}

# tolerations: []

# affinity: {}
